<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Api_docs extends CI_Controller
{
    public function index()
    {
        $data = [
            'title' => 'AR Alumni API Documentation'
        ];

        $this->load->view('templates/header', $data);
        $this->load->view('api_docs/swagger_ui', $data);
        $this->load->view('templates/footer');
    }

    public function openapi()
    {
        $serverUrl = rtrim(site_url(''), '/');

        $spec = [
            'openapi' => '3.0.3',
            'info' => [
                'title' => 'AR Alumni Public Developer API',
                'description' => 'Public API for retrieving the featured alumnus and public alumni profile data for AR client applications.',
                'version' => '1.0.0'
            ],
            'servers' => [
                [
                    'url' => $serverUrl,
                    'description' => 'Local CodeIgniter development server'
                ]
            ],
            'tags' => [
                [
                    'name' => 'System',
                    'description' => 'API health and availability'
                ],
                [
                    'name' => 'Featured Alumni',
                    'description' => 'Endpoints for Alumni of the Day data'
                ],
                [
                    'name' => 'Alumni Profiles',
                    'description' => 'Endpoints for public alumni profile data'
                ]
            ],
            'components' => [
                'securitySchemes' => [
                    'BearerAuth' => [
                        'type' => 'http',
                        'scheme' => 'bearer',
                        'bearerFormat' => 'API Key',
                        'description' => 'Enter the API key generated by the developer dashboard.'
                    ]
                ],
                'schemas' => [
                    'ApiSuccessResponse' => [
                        'type' => 'object',
                        'properties' => [
                            'status' => [
                                'type' => 'string',
                                'example' => 'success'
                            ],
                            'message' => [
                                'type' => 'string',
                                'example' => 'Featured alumnus retrieved successfully.'
                            ],
                            'data' => [
                                '$ref' => '#/components/schemas/FeaturedAlumnus'
                            ]
                        ]
                    ],
                    'ApiErrorResponse' => [
                        'type' => 'object',
                        'properties' => [
                            'status' => [
                                'type' => 'string',
                                'example' => 'error'
                            ],
                            'message' => [
                                'type' => 'string',
                                'example' => 'Missing bearer token. Use Authorization: Bearer YOUR_API_KEY.'
                            ]
                        ]
                    ],
                    'FeaturedAlumnus' => [
                        'type' => 'object',
                        'properties' => [
                            'feature_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2026-04-29'
                            ],
                            'selected_at' => [
                                'type' => 'string',
                                'example' => '2026-04-28 14:05:58'
                            ],
                            'alumni_id' => [
                                'type' => 'integer',
                                'example' => 5
                            ],
                            'full_name' => [
                                'type' => 'string',
                                'example' => 'Test Alumni'
                            ],
                            'email' => [
                                'type' => 'string',
                                'example' => 'test.alumni@eastminster.ac.uk'
                            ],
                            'personal_info' => [
                                'type' => 'string',
                                'example' => 'Based in London, United Kingdom.'
                            ],
                            'headline' => [
                                'type' => 'string',
                                'example' => 'Junior Software Engineer | Web API Developer'
                            ],
                            'biography' => [
                                'type' => 'string',
                                'example' => 'I graduated from the University of Eastminster with a background in software engineering.'
                            ],
                            'linkedin_url' => [
                                'type' => 'string',
                                'example' => 'https://www.linkedin.com/in/test-alumni'
                            ],
                            'profile_image_path' => [
                                'type' => 'string',
                                'example' => 'uploads/profiles/example.jpg'
                            ],
                            'profile_image_url' => [
                                'type' => 'string',
                                'example' => base_url('uploads/profiles/example.jpg')
                            ],
                            'profile_completion_percent' => [
                                'type' => 'integer',
                                'example' => 100
                            ],
                            'sections' => [
                                '$ref' => '#/components/schemas/ProfileSections'
                            ]
                        ]
                    ],
                    'ProfileSections' => [
                        'type' => 'object',
                        'properties' => [
                            'degrees' => [
                                'type' => 'array',
                                'items' => [
                                    '$ref' => '#/components/schemas/Degree'
                                ]
                            ],
                            'certifications' => [
                                'type' => 'array',
                                'items' => [
                                    '$ref' => '#/components/schemas/Certification'
                                ]
                            ],
                            'licences' => [
                                'type' => 'array',
                                'items' => [
                                    '$ref' => '#/components/schemas/Licence'
                                ]
                            ],
                            'courses' => [
                                'type' => 'array',
                                'items' => [
                                    '$ref' => '#/components/schemas/Course'
                                ]
                            ],
                            'employment_history' => [
                                'type' => 'array',
                                'items' => [
                                    '$ref' => '#/components/schemas/Employment'
                                ]
                            ]
                        ]
                    ],
                    'Degree' => [
                        'type' => 'object',
                        'properties' => [
                            'degree_name' => [
                                'type' => 'string',
                                'example' => 'BSc Software Engineering'
                            ],
                            'university_name' => [
                                'type' => 'string',
                                'example' => 'University of Eastminster'
                            ],
                            'official_url' => [
                                'type' => 'string',
                                'example' => 'https://www.eastminster.ac.uk/courses/software-engineering'
                            ],
                            'completion_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2025-07-15'
                            ]
                        ]
                    ],
                    'Certification' => [
                        'type' => 'object',
                        'properties' => [
                            'certification_name' => [
                                'type' => 'string',
                                'example' => 'Google Cybersecurity Professional Certificate'
                            ],
                            'provider_name' => [
                                'type' => 'string',
                                'example' => 'Google / Coursera'
                            ],
                            'official_url' => [
                                'type' => 'string',
                                'example' => 'https://www.coursera.org/professional-certificates/google-cybersecurity'
                            ],
                            'completion_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2025-08-20'
                            ]
                        ]
                    ],
                    'Licence' => [
                        'type' => 'object',
                        'properties' => [
                            'licence_name' => [
                                'type' => 'string',
                                'example' => 'AWS Certified Cloud Practitioner'
                            ],
                            'awarding_body' => [
                                'type' => 'string',
                                'example' => 'Amazon Web Services'
                            ],
                            'official_url' => [
                                'type' => 'string',
                                'example' => 'https://aws.amazon.com/certification/certified-cloud-practitioner/'
                            ],
                            'completion_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2025-09-10'
                            ]
                        ]
                    ],
                    'Course' => [
                        'type' => 'object',
                        'properties' => [
                            'course_name' => [
                                'type' => 'string',
                                'example' => 'Introduction to Web APIs and RESTful Services'
                            ],
                            'provider_name' => [
                                'type' => 'string',
                                'example' => 'IBM / Coursera'
                            ],
                            'official_url' => [
                                'type' => 'string',
                                'example' => 'https://www.coursera.org/learn/introduction-to-apis'
                            ],
                            'completion_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2025-06-05'
                            ]
                        ]
                    ],
                    'Employment' => [
                        'type' => 'object',
                        'properties' => [
                            'company_name' => [
                                'type' => 'string',
                                'example' => 'Phantasmagoria Ltd'
                            ],
                            'job_title' => [
                                'type' => 'string',
                                'example' => 'Junior Backend Developer'
                            ],
                            'start_date' => [
                                'type' => 'string',
                                'format' => 'date',
                                'example' => '2025-08-01'
                            ],
                            'end_date' => [
                                'type' => 'string',
                                'nullable' => true,
                                'example' => null
                            ],
                            'is_current' => [
                                'type' => 'integer',
                                'example' => 1
                            ],
                            'description' => [
                                'type' => 'string',
                                'example' => 'Developed backend features for educational technology platforms.'
                            ]
                        ]
                    ]
                ]
            ],
            'paths' => [
                '/api/v1/health' => [
                    'get' => [
                        'tags' => ['System'],
                        'summary' => 'Check API health',
                        'description' => 'Returns a simple response confirming that the public API is running.',
                        'security' => [],
                        'responses' => [
                            '200' => [
                                'description' => 'API is running'
                            ]
                        ]
                    ]
                ],
                '/api/v1/featured-today' => [
                    'get' => [
                        'tags' => ['Featured Alumni'],
                        'summary' => 'Get today’s featured alumnus',
                        'description' => 'Returns the Alumni of the Day for the current server date. Requires a bearer API key.',
                        'security' => [
                            [
                                'BearerAuth' => []
                            ]
                        ],
                        'responses' => [
                            '200' => [
                                'description' => 'Featured alumnus returned successfully',
                                'content' => [
                                    'application/json' => [
                                        'schema' => [
                                            '$ref' => '#/components/schemas/ApiSuccessResponse'
                                        ]
                                    ]
                                ]
                            ],
                            '401' => [
                                'description' => 'Missing, invalid, or revoked bearer token',
                                'content' => [
                                    'application/json' => [
                                        'schema' => [
                                            '$ref' => '#/components/schemas/ApiErrorResponse'
                                        ]
                                    ]
                                ]
                            ],
                            '404' => [
                                'description' => 'No featured alumnus selected for today'
                            ]
                        ]
                    ]
                ],
                '/api/v1/featured/{date}' => [
                    'get' => [
                        'tags' => ['Featured Alumni'],
                        'summary' => 'Get featured alumnus by date',
                        'description' => 'Returns the featured alumnus for a selected date in YYYY-MM-DD format.',
                        'security' => [
                            [
                                'BearerAuth' => []
                            ]
                        ],
                        'parameters' => [
                            [
                                'name' => 'date',
                                'in' => 'path',
                                'required' => true,
                                'description' => 'Feature date using YYYY-MM-DD format.',
                                'schema' => [
                                    'type' => 'string',
                                    'format' => 'date',
                                    'example' => '2026-04-29'
                                ]
                            ]
                        ],
                        'responses' => [
                            '200' => [
                                'description' => 'Featured alumnus returned successfully'
                            ],
                            '400' => [
                                'description' => 'Invalid date format'
                            ],
                            '401' => [
                                'description' => 'Missing, invalid, or revoked bearer token'
                            ],
                            '404' => [
                                'description' => 'No featured alumnus selected for this date'
                            ]
                        ]
                    ]
                ],
                '/api/v1/alumni/{id}' => [
                    'get' => [
                        'tags' => ['Alumni Profiles'],
                        'summary' => 'Get public alumni profile by ID',
                        'description' => 'Returns the public profile data for a selected alumnus.',
                        'security' => [
                            [
                                'BearerAuth' => []
                            ]
                        ],
                        'parameters' => [
                            [
                                'name' => 'id',
                                'in' => 'path',
                                'required' => true,
                                'description' => 'Alumni user ID.',
                                'schema' => [
                                    'type' => 'integer',
                                    'example' => 5
                                ]
                            ]
                        ],
                        'responses' => [
                            '200' => [
                                'description' => 'Alumni profile returned successfully'
                            ],
                            '401' => [
                                'description' => 'Missing, invalid, or revoked bearer token'
                            ],
                            '404' => [
                                'description' => 'Public alumni profile not found'
                            ]
                        ]
                    ]
                ]
            ]
        ];

        $this->output
            ->set_content_type('application/json')
            ->set_output(json_encode($spec, JSON_PRETTY_PRINT));
    }
}